version: "3.7"
services:
  app:
    container_name: server-client-app
    image: golang:1.17-alpine
    volumes:
      - ./src:/go/src
    command: >
      /bin/sh -c "
      apk add build-base;
      tail -f > /dev/null"